apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp
  labels:
    name: webapp
spec:
  replicas: 1
  selector:
    name: webapp
  template:
    metadata:
      labels:
        name: webapp
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9999"
        prometheus.io/path: ""
    spec:
      containers:
      - name: webapp
        image: insightdatascience/webapp-demo:prometheus
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        - containerPort: 9999
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
